In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("batsmen_10.csv")

In [3]:
dataset = dataset.fillna(0) #fill empty space with 0
dataset

,name,mt,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,4s,6s,Ct,St,capped
0,Rajesh Bishnoi,First-class,3,5,0,49,25,9.80,168.0,29.16,0,0,8.0,0.0,0,0.0,0
1,Rajesh Bishnoi,List A,10,6,2,34,17,8.50,95.0,35.78,0,0,3.0,0.0,4,0.0,0
2,Rajesh Bishnoi,T20s,1,1,0,1,1,1.00,3.0,33.33,0,0,0.0,0.0,0,0.0,0
3,Chetan Bist,First-class,25,40,3,1137,159,30.72,2391.0,47.55,2,8,142.0,10.0,91,2.0,0
4,Chetan Bist,List A,13,11,2,219,82,24.33,342.0,64.03,0,1,15.0,5.0,15,0.0,0
5,Chetan Bist,T20s,10,6,1,79,41,15.80,68.0,116.17,0,0,5.0,4.0,10,5.0,0
6,robin bist,First-class,99,164,25,6634,220,47.72,14534.0,45.64,15,34,746.0,52.0,47,0.0,0
7,robin bist,List A,51,50,6,1299,109,29.52,1929.0,67.34,1,8,94.0,8.0,24,0.0,0
8,robin bist,T20s,20,18,2,193,30,12.06,232.0,83.18,0,0,13.0,0.0,7,0.0,0
9,Amitkumar Gautam,First-class,19,33,1,1161,159,36.28,2718.0,42.71,4,6,154.0,14.0,13,0.0,0
10,Amitkumar Gautam,List A,12,12,1,293,149,26.63,449.0,65.25,1,1,36.0,4.0,1,0.0,0
11,arjit gupta,First-class,10,19,0,448,77,23.57,878.0,51.02,0,2,67.0,3.0,5,0.0,0
12,arjit gupta,List A,16,15,2,416,107,32.00,503.0,82.70,1,2,35.0,15.0,2,0.0,0
13,arjit gupta,T20s,11,10,1,156,72,17.33,131.0,119.08,0,2,10.0,10.0,2,0.0,0
14,Manendar Singh,First-class,11,20,2,351,63,19.50,949.0,36.98,0,2,57.0,0.0,9,0.0,0
15,Manendar Singh,List A,11,11,1,531,118,53.10,725.0,73.24,2,3,45.0,9.0,9,1.0,0
16,Manendar Singh,T20s,4,4,0,22,12,5.50,34.0,64.70,0,0,1.0,1.0,4,0.0,0
17,Chaitanya Bishnoi,First-class,37,68,5,1706,94,27.07,4459.0,38.25,0,15,204.0,3.0,20,0.0,0
18,Chaitanya Bishnoi,List A,21,21,3,645,88,35.83,1009.0,63.92,0,5,52.0,10.0,4,0.0,0
19,Chaitanya Bishnoi,T20s,14,13,1,211,65,17.58,223.0,94.61,0,1,16.0,5.0,2,0.0,0
20,himanshu rana,First-class,24,43,1,1386,164,33.00,2682.0,51.67,3,8,168.0,5.0,15,0.0,0
21,himanshu rana,List A,14,13,1,406,89,33.83,492.0,82.52,0,2,32.0,7.0,8,0.0,0
22,himanshu rana,T20s,11,10,1,172,59,19.11,144.0,119.44,0,1,18.0,4.0,1,0.0,0
23,Subham rohilla,First-class,22,40,1,964,118,24.71,2046.0,47.11,2,5,113.0,2.0,12,0.0,0
24,Subham rohilla,List A,17,17,1,489,118,30.56,655.0,74.65,1,3,54.0,2.0,4,0.0,0
25,Subham rohilla,T20s,10,10,0,180,44,18.00,187.0,96.25,0,0,23.0,0.0,1,0.0,0
26,rohit sharma,First-class,24,41,2,983,107,25.20,2362.0,41.61,1,7,99.0,2.0,29,3.0,1
27,rohit sharma,List A,11,10,0,188,50,18.80,328.0,57.31,0,1,13.0,1.0,8,0.0,1
28,rohit sharma,T20s,7,6,1,57,22,11.40,58.0,98.27,0,0,6.0,0.0,3,1.0,1
29,manoj tiwari,First-class,114,180,16,8258,267,50.35,14874.0,55.51,26,34,0.0,0.0,120,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Dinesh Karthik,T20s,257,228,41,5107,90,27.31,3855.0,132.47,0,25,505.0,147.0,159,55.0,1
76,Ambati Rayudu,First-class,97,156,21,6151,210,45.56,0.0,0.00,16,34,0.0,0.0,74,0.0,1
77,Ambati Rayudu,List A,151,141,23,4856,124,41.15,0.0,0.00,5,36,0.0,0.0,65,0.0,1
78,Ambati Rayudu,T20s,195,184,24,4235,100,26.46,3362.0,125.96,1,23,360.0,148.0,75,3.0,1
79,Manish Pandey,First-class,87,134,16,6111,238,51.78,9425.0,64.83,19,27,713.0,93.0,124,0.0,1
80,Manish Pandey,List A,139,131,27,4504,117,43.30,4931.0,91.34,8,27,369.0,94.0,68,0.0,1
81,Manish Pandey,T20s,197,182,35,4166,114,28.34,3504.0,118.89,1,20,351.0,112.0,95,2.0,1
82,Mayank Agarwal,First-class,48,81,6,3794,304,50.58,6237.0,60.83,8,22,494.0,40.0,30,0.0,1
83,Mayank Agarwal,List A,75,75,1,3605,176,48.71,3579.0,100.72,12,14,448.0,63.0,28,0.0,1
84,Mayank Agarwal,T20s,111,106,6,2340,111,23.40,1789.0,130.79,1,15,236.0,82.0,38,0.0,1
85,Cheteshwar Pujara,First-class,184,301,35,14474,352,54.41,0.0,0.00,48,49,0.0,0.0,125,0.0,1
86,Cheteshwar Pujara,List A,103,101,19,4445,158,54.20,0.0,0.00,11,29,0.0,0.0,39,0.0,1
87,Cheteshwar Pujara,T20s,58,50,7,1096,81,25.48,1042.0,105.18,0,6,121.0,18.0,30,0.0,1
88,Murali Vijay,First-class,131,220,7,9116,266,42.79,18471.0,49.35,25,38,1112.0,107.0,112,0.0,1
89,Murali Vijay,List A,86,85,2,3360,155,40.48,4206.0,79.88,7,18,323.0,73.0,39,0.0,1
90,Murali Vijay,T20s,154,152,5,3739,127,25.43,3076.0,121.55,2,20,347.0,133.0,62,0.0,1
91,Naman Ojha,First-class,143,244,16,9560,219,41.92,0.0,0.00,21,55,0.0,0.0,417,54.0,0
92,Naman Ojha,List A,133,129,7,3933,167,32.23,0.0,0.00,8,21,0.0,0.0,154,43.0,0
93,Naman Ojha,T20s,170,150,20,2706,94,20.81,2301.0,117.60,0,13,237.0,127.0,107,24.0,0
94,Srikar Bharat,First-class,61,100,6,3433,308,36.52,5921.0,57.98,6,19,434.0,58.0,208,23.0,0
95,Srikar Bharat,List A,46,46,2,1281,125,29.11,1842.0,69.54,3,5,132.0,15.0,52,11.0,0
96,Srikar Bharat,T20s,31,29,2,369,51,13.66,406.0,90.88,0,1,34.0,9.0,27,5.0,0
97,ricky Bhui,First-class,34,52,2,2293,187,45.86,4613.0,49.70,8,10,256.0,36.0,20,0.0,0
98,ricky Bhui,List A,31,29,8,984,103,46.85,1255.0,78.40,1,7,75.0,34.0,13,0.0,0
99,ricky Bhui,T20s,28,28,7,598,73,28.47,504.0,118.65,0,5,44.0,27.0,4,0.0,0
100,Jyothi Sai Krishan,First-class,8,13,1,377,82,31.41,893.0,42.21,0,3,42.0,3.0,4,0.0,0
101,Jyothi Sai Krishan,List A,11,11,1,321,72,32.10,416.0,77.16,0,4,31.0,5.0,3,0.0,0
102,Jyothi Sai Krishan,T20s,12,11,1,151,33,15.10,163.0,92.63,0,0,15.0,0.0,4,0.0,0
103,z,First-class,13,22,2,547,92,27.35,1438.0,38.03,0,4,70.0,0.0,7,0.0,0
104,Himanshu Asnora,T20s,2,2,0,8,6,4.00,13.0,61.53,0,0,0.0,0.0,2,0.0,0

In [4]:
y = dataset.iloc[: , -1]

In [5]:
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     1
27     1
28     1
29     1
      ..
75     1
76     1
77     1
78     1
79     1
80     1
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     1
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
Name: capped, Length: 105, dtype: int64

In [6]:
X = dataset.iloc[: , 0:16]

In [7]:
X

,name,mt,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,4s,6s,Ct,St
0,Rajesh Bishnoi,First-class,3,5,0,49,25,9.80,168.0,29.16,0,0,8.0,0.0,0,0.0
1,Rajesh Bishnoi,List A,10,6,2,34,17,8.50,95.0,35.78,0,0,3.0,0.0,4,0.0
2,Rajesh Bishnoi,T20s,1,1,0,1,1,1.00,3.0,33.33,0,0,0.0,0.0,0,0.0
3,Chetan Bist,First-class,25,40,3,1137,159,30.72,2391.0,47.55,2,8,142.0,10.0,91,2.0
4,Chetan Bist,List A,13,11,2,219,82,24.33,342.0,64.03,0,1,15.0,5.0,15,0.0
5,Chetan Bist,T20s,10,6,1,79,41,15.80,68.0,116.17,0,0,5.0,4.0,10,5.0
6,robin bist,First-class,99,164,25,6634,220,47.72,14534.0,45.64,15,34,746.0,52.0,47,0.0
7,robin bist,List A,51,50,6,1299,109,29.52,1929.0,67.34,1,8,94.0,8.0,24,0.0
8,robin bist,T20s,20,18,2,193,30,12.06,232.0,83.18,0,0,13.0,0.0,7,0.0
9,Amitkumar Gautam,First-class,19,33,1,1161,159,36.28,2718.0,42.71,4,6,154.0,14.0,13,0.0
10,Amitkumar Gautam,List A,12,12,1,293,149,26.63,449.0,65.25,1,1,36.0,4.0,1,0.0
11,arjit gupta,First-class,10,19,0,448,77,23.57,878.0,51.02,0,2,67.0,3.0,5,0.0
12,arjit gupta,List A,16,15,2,416,107,32.00,503.0,82.70,1,2,35.0,15.0,2,0.0
13,arjit gupta,T20s,11,10,1,156,72,17.33,131.0,119.08,0,2,10.0,10.0,2,0.0
14,Manendar Singh,First-class,11,20,2,351,63,19.50,949.0,36.98,0,2,57.0,0.0,9,0.0
15,Manendar Singh,List A,11,11,1,531,118,53.10,725.0,73.24,2,3,45.0,9.0,9,1.0
16,Manendar Singh,T20s,4,4,0,22,12,5.50,34.0,64.70,0,0,1.0,1.0,4,0.0
17,Chaitanya Bishnoi,First-class,37,68,5,1706,94,27.07,4459.0,38.25,0,15,204.0,3.0,20,0.0
18,Chaitanya Bishnoi,List A,21,21,3,645,88,35.83,1009.0,63.92,0,5,52.0,10.0,4,0.0
19,Chaitanya Bishnoi,T20s,14,13,1,211,65,17.58,223.0,94.61,0,1,16.0,5.0,2,0.0
20,himanshu rana,First-class,24,43,1,1386,164,33.00,2682.0,51.67,3,8,168.0,5.0,15,0.0
21,himanshu rana,List A,14,13,1,406,89,33.83,492.0,82.52,0,2,32.0,7.0,8,0.0
22,himanshu rana,T20s,11,10,1,172,59,19.11,144.0,119.44,0,1,18.0,4.0,1,0.0
23,Subham rohilla,First-class,22,40,1,964,118,24.71,2046.0,47.11,2,5,113.0,2.0,12,0.0
24,Subham rohilla,List A,17,17,1,489,118,30.56,655.0,74.65,1,3,54.0,2.0,4,0.0
25,Subham rohilla,T20s,10,10,0,180,44,18.00,187.0,96.25,0,0,23.0,0.0,1,0.0
26,rohit sharma,First-class,24,41,2,983,107,25.20,2362.0,41.61,1,7,99.0,2.0,29,3.0
27,rohit sharma,List A,11,10,0,188,50,18.80,328.0,57.31,0,1,13.0,1.0,8,0.0
28,rohit sharma,T20s,7,6,1,57,22,11.40,58.0,98.27,0,0,6.0,0.0,3,1.0
29,manoj tiwari,First-class,114,180,16,8258,267,50.35,14874.0,55.51,26,34,0.0,0.0,120,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Dinesh Karthik,T20s,257,228,41,5107,90,27.31,3855.0,132.47,0,25,505.0,147.0,159,55.0
76,Ambati Rayudu,First-class,97,156,21,6151,210,45.56,0.0,0.00,16,34,0.0,0.0,74,0.0
77,Ambati Rayudu,List A,151,141,23,4856,124,41.15,0.0,0.00,5,36,0.0,0.0,65,0.0
78,Ambati Rayudu,T20s,195,184,24,4235,100,26.46,3362.0,125.96,1,23,360.0,148.0,75,3.0
79,Manish Pandey,First-class,87,134,16,6111,238,51.78,9425.0,64.83,19,27,713.0,93.0,124,0.0
80,Manish Pandey,List A,139,131,27,4504,117,43.30,4931.0,91.34,8,27,369.0,94.0,68,0.0
81,Manish Pandey,T20s,197,182,35,4166,114,28.34,3504.0,118.89,1,20,351.0,112.0,95,2.0
82,Mayank Agarwal,First-class,48,81,6,3794,304,50.58,6237.0,60.83,8,22,494.0,40.0,30,0.0
83,Mayank Agarwal,List A,75,75,1,3605,176,48.71,3579.0,100.72,12,14,448.0,63.0,28,0.0
84,Mayank Agarwal,T20s,111,106,6,2340,111,23.40,1789.0,130.79,1,15,236.0,82.0,38,0.0
85,Cheteshwar Pujara,First-class,184,301,35,14474,352,54.41,0.0,0.00,48,49,0.0,0.0,125,0.0
86,Cheteshwar Pujara,List A,103,101,19,4445,158,54.20,0.0,0.00,11,29,0.0,0.0,39,0.0
87,Cheteshwar Pujara,T20s,58,50,7,1096,81,25.48,1042.0,105.18,0,6,121.0,18.0,30,0.0
88,Murali Vijay,First-class,131,220,7,9116,266,42.79,18471.0,49.35,25,38,1112.0,107.0,112,0.0
89,Murali Vijay,List A,86,85,2,3360,155,40.48,4206.0,79.88,7,18,323.0,73.0,39,0.0
90,Murali Vijay,T20s,154,152,5,3739,127,25.43,3076.0,121.55,2,20,347.0,133.0,62,0.0
91,Naman Ojha,First-class,143,244,16,9560,219,41.92,0.0,0.00,21,55,0.0,0.0,417,54.0
92,Naman Ojha,List A,133,129,7,3933,167,32.23,0.0,0.00,8,21,0.0,0.0,154,43.0
93,Naman Ojha,T20s,170,150,20,2706,94,20.81,2301.0,117.60,0,13,237.0,127.0,107,24.0
94,Srikar Bharat,First-class,61,100,6,3433,308,36.52,5921.0,57.98,6,19,434.0,58.0,208,23.0
95,Srikar Bharat,List A,46,46,2,1281,125,29.11,1842.0,69.54,3,5,132.0,15.0,52,11.0
96,Srikar Bharat,T20s,31,29,2,369,51,13.66,406.0,90.88,0,1,34.0,9.0,27,5.0
97,ricky Bhui,First-class,34,52,2,2293,187,45.86,4613.0,49.70,8,10,256.0,36.0,20,0.0
98,ricky Bhui,List A,31,29,8,984,103,46.85,1255.0,78.40,1,7,75.0,34.0,13,0.0
99,ricky Bhui,T20s,28,28,7,598,73,28.47,504.0,118.65,0,5,44.0,27.0,4,0.0
100,Jyothi Sai Krishan,First-class,8,13,1,377,82,31.41,893.0,42.21,0,3,42.0,3.0,4,0.0
101,Jyothi Sai Krishan,List A,11,11,1,321,72,32.10,416.0,77.16,0,4,31.0,5.0,3,0.0
102,Jyothi Sai Krishan,T20s,12,11,1,151,33,15.10,163.0,92.63,0,0,15.0,0.0,4,0.0
103,z,First-class,13,22,2,547,92,27.35,1438.0,38.03,0,4,70.0,0.0,7,0.0
104,Himanshu Asnora,T20s,2,2,0,8,6,4.00,13.0,61.53,0,0,0.0,0.0,2,0.0

In [8]:
name = dataset.iloc[: ,0 ]

name

In [9]:
mt = X.iloc[:,1]
mt

0      First-class
1           List A
2             T20s
3      First-class
4           List A
5             T20s
6      First-class
7           List A
8             T20s
9      First-class
10          List A
11     First-class
12          List A
13            T20s
14     First-class
15          List A
16            T20s
17     First-class
18          List A
19            T20s
20     First-class
21          List A
22            T20s
23     First-class
24          List A
25            T20s
26     First-class
27          List A
28            T20s
29     First-class
          ...
75            T20s
76     First-class
77          List A
78            T20s
79     First-class
80          List A
81            T20s
82     First-class
83          List A
84            T20s
85     First-class
86          List A
87            T20s
88     First-class
89          List A
90            T20s
91     First-class
92          List A
93            T20s
94     First-class
95          List A
96            T20s
97     First-class
98          List A
99            T20s
100    First-class
101         List A
102           T20s
103    First-class
104           T20s
Name: mt, Length: 105, dtype: object

In [10]:

from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
mt_new = labelencoder_x.fit_transform(mt)
X.iloc[:,1]= mt_new

In [23]:
# preprocess :  categorical variable
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
name_new = labelencoder_x.fit_transform(name)
X.iloc[:,0]=name_new.astype(int)

In [24]:
X

,name,mt,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,4s,6s,Ct,St
0,22,0,3,5,0,49,25,9.80,168.0,29.16,0,0,8.0,0.0,0,0.0
1,22,1,10,6,2,34,17,8.50,95.0,35.78,0,0,3.0,0.0,4,0.0
2,22,2,1,1,0,1,1,1.00,3.0,33.33,0,0,0.0,0.0,0,0.0
3,8,0,25,40,3,1137,159,30.72,2391.0,47.55,2,8,142.0,10.0,91,2.0
4,8,1,13,11,2,219,82,24.33,342.0,64.03,0,1,15.0,5.0,15,0.0
5,8,2,10,6,1,79,41,15.80,68.0,116.17,0,0,5.0,4.0,10,5.0
6,32,0,99,164,25,6634,220,47.72,14534.0,45.64,15,34,746.0,52.0,47,0.0
7,32,1,51,50,6,1299,109,29.52,1929.0,67.34,1,8,94.0,8.0,24,0.0
8,32,2,20,18,2,193,30,12.06,232.0,83.18,0,0,13.0,0.0,7,0.0
9,4,0,19,33,1,1161,159,36.28,2718.0,42.71,4,6,154.0,14.0,13,0.0
10,4,1,12,12,1,293,149,26.63,449.0,65.25,1,1,36.0,4.0,1,0.0
11,27,0,10,19,0,448,77,23.57,878.0,51.02,0,2,67.0,3.0,5,0.0
12,27,1,16,15,2,416,107,32.00,503.0,82.70,1,2,35.0,15.0,2,0.0
13,27,2,11,10,1,156,72,17.33,131.0,119.08,0,2,10.0,10.0,2,0.0
14,16,0,11,20,2,351,63,19.50,949.0,36.98,0,2,57.0,0.0,9,0.0
15,16,1,11,11,1,531,118,53.10,725.0,73.24,2,3,45.0,9.0,9,1.0
16,16,2,4,4,0,22,12,5.50,34.0,64.70,0,0,1.0,1.0,4,0.0
17,7,0,37,68,5,1706,94,27.07,4459.0,38.25,0,15,204.0,3.0,20,0.0
18,7,1,21,21,3,645,88,35.83,1009.0,63.92,0,5,52.0,10.0,4,0.0
19,7,2,14,13,1,211,65,17.58,223.0,94.61,0,1,16.0,5.0,2,0.0
20,29,0,24,43,1,1386,164,33.00,2682.0,51.67,3,8,168.0,5.0,15,0.0
21,29,1,14,13,1,406,89,33.83,492.0,82.52,0,2,32.0,7.0,8,0.0
22,29,2,11,10,1,172,59,19.11,144.0,119.44,0,1,18.0,4.0,1,0.0
23,25,0,22,40,1,964,118,24.71,2046.0,47.11,2,5,113.0,2.0,12,0.0
24,25,1,17,17,1,489,118,30.56,655.0,74.65,1,3,54.0,2.0,4,0.0
25,25,2,10,10,0,180,44,18.00,187.0,96.25,0,0,23.0,0.0,1,0.0
26,33,0,24,41,2,983,107,25.20,2362.0,41.61,1,7,99.0,2.0,29,3.0
27,33,1,11,10,0,188,50,18.80,328.0,57.31,0,1,13.0,1.0,8,0.0
28,33,2,7,6,1,57,22,11.40,58.0,98.27,0,0,6.0,0.0,3,1.0
29,30,0,114,180,16,8258,267,50.35,14874.0,55.51,26,34,0.0,0.0,120,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,10,2,257,228,41,5107,90,27.31,3855.0,132.47,0,25,505.0,147.0,159,55.0
76,3,0,97,156,21,6151,210,45.56,0.0,0.00,16,34,0.0,0.0,74,0.0
77,3,1,151,141,23,4856,124,41.15,0.0,0.00,5,36,0.0,0.0,65,0.0
78,3,2,195,184,24,4235,100,26.46,3362.0,125.96,1,23,360.0,148.0,75,3.0
79,17,0,87,134,16,6111,238,51.78,9425.0,64.83,19,27,713.0,93.0,124,0.0
80,17,1,139,131,27,4504,117,43.30,4931.0,91.34,8,27,369.0,94.0,68,0.0
81,17,2,197,182,35,4166,114,28.34,3504.0,118.89,1,20,351.0,112.0,95,2.0
82,18,0,48,81,6,3794,304,50.58,6237.0,60.83,8,22,494.0,40.0,30,0.0
83,18,1,75,75,1,3605,176,48.71,3579.0,100.72,12,14,448.0,63.0,28,0.0
84,18,2,111,106,6,2340,111,23.40,1789.0,130.79,1,15,236.0,82.0,38,0.0
85,9,0,184,301,35,14474,352,54.41,0.0,0.00,48,49,0.0,0.0,125,0.0
86,9,1,103,101,19,4445,158,54.20,0.0,0.00,11,29,0.0,0.0,39,0.0
87,9,2,58,50,7,1096,81,25.48,1042.0,105.18,0,6,121.0,18.0,30,0.0
88,19,0,131,220,7,9116,266,42.79,18471.0,49.35,25,38,1112.0,107.0,112,0.0
89,19,1,86,85,2,3360,155,40.48,4206.0,79.88,7,18,323.0,73.0,39,0.0
90,19,2,154,152,5,3739,127,25.43,3076.0,121.55,2,20,347.0,133.0,62,0.0
91,20,0,143,244,16,9560,219,41.92,0.0,0.00,21,55,0.0,0.0,417,54.0
92,20,1,133,129,7,3933,167,32.23,0.0,0.00,8,21,0.0,0.0,154,43.0
93,20,2,170,150,20,2706,94,20.81,2301.0,117.60,0,13,237.0,127.0,107,24.0
94,24,0,61,100,6,3433,308,36.52,5921.0,57.98,6,19,434.0,58.0,208,23.0
95,24,1,46,46,2,1281,125,29.11,1842.0,69.54,3,5,132.0,15.0,52,11.0
96,24,2,31,29,2,369,51,13.66,406.0,90.88,0,1,34.0,9.0,27,5.0
97,31,0,34,52,2,2293,187,45.86,4613.0,49.70,8,10,256.0,36.0,20,0.0
98,31,1,31,29,8,984,103,46.85,1255.0,78.40,1,7,75.0,34.0,13,0.0
99,31,2,28,28,7,598,73,28.47,504.0,118.65,0,5,44.0,27.0,4,0.0
100,13,0,8,13,1,377,82,31.41,893.0,42.21,0,3,42.0,3.0,4,0.0
101,13,1,11,11,1,321,72,32.10,416.0,77.16,0,4,31.0,5.0,3,0.0
102,13,2,12,11,1,151,33,15.10,163.0,92.63,0,0,15.0,0.0,4,0.0
103,36,0,13,22,2,547,92,27.35,1438.0,38.03,0,4,70.0,0.0,7,0.0
104,12,2,2,2,0,8,6,4.00,13.0,61.53,0,0,0.0,0.0,2,0.0

In [13]:
# from sklearn.preprocessing  import OneHotEncoder
# onehotencoder = OneHotEncoder(categorical_features=[0])
# X = onehotencoder.fit_transform(X).toarray()

In [14]:
# from sklearn.preprocessing  import OneHotEncoder
# onehotencoder = OneHotEncoder(categorical_features=[1])
# X = onehotencoder.fit_transform(X).toarray()

In [20]:
X

KeyError: "['Rajesh Bishnoi\\xa0\\xa0\\xa0' 'Rajesh Bishnoi\\xa0\\xa0\\xa0'\n 'Rajesh Bishnoi\\xa0\\xa0\\xa0' 'Chetan Bist\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0'\n 'Chetan Bist\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0'\n 'Chetan Bist\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0' 'robin bist' 'robin bist'\n 'robin bist' 'Amitkumar Gautam' 'Amitkumar Gautam' 'arjit gupta'\n 'arjit gupta' 'arjit gupta' 'Manendar Singh' 'Manendar Singh'\n 'Manendar Singh' 'Chaitanya Bishnoi' 'Chaitanya Bishnoi'\n 'Chaitanya Bishnoi' 'himanshu rana' 'himanshu rana' 'himanshu rana'\n 'Subham rohilla' 'Subham rohilla' 'Subham rohilla' 'rohit sharma'\n 'rohit sharma' 'rohit sharma' 'manoj tiwari' 'manoj tiwari'\n 'manoj tiwari' 'Boddupalli Amit\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0'\n 'Boddupalli Amit\\xa0\\xa0\\xa0\\xa0\\xa0\\xa0' 'Sudip Chatterjee'\n 'Sudip Chatterjee' 'Sudip Chatterjee' 'Abhimanyu Easwaran'\n 'Abhimanyu Easwaran' 'Abhimanyu Easwaran' 'Abhishek Raman'\n 'Abhishek Raman' 'Abhishek Raman' 'hanuma Vihari' 'hanuma Vihari'\n 'hanuma Vihari' 'Bodapati Sumanth' 'Bodapati Sumanth' 'Bodapati Sumanth'\n 'Gautam Gambhir' 'Gautam Gambhir' 'Gautam Gambhir' 'shikhar Dhawan'\n 'shikhar Dhawan' 'shikhar Dhawan' 'virat kohli' 'virat kohli'\n 'virat kohli' 'Lokesh Rahul' 'Lokesh Rahul' 'Lokesh Rahul' 'MS Dhoni'\n 'MS Dhoni' 'MS Dhoni' 'Prithvi Shaw' 'Prithvi Shaw' 'Prithvi Shaw'\n 'Rishabh Pant' 'Rishabh Pant' 'Rishabh Pant' 'Ajinkya Rahane'\n 'Ajinkya Rahane' 'Ajinkya Rahane' 'Dinesh Karthik' 'Dinesh Karthik'\n 'Dinesh Karthik' 'Ambati Rayudu' 'Ambati Rayudu' 'Ambati Rayudu'\n 'Manish Pandey' 'Manish Pandey' 'Manish Pandey' 'Mayank Agarwal'\n 'Mayank Agarwal' 'Mayank Agarwal' 'Cheteshwar Pujara' 'Cheteshwar Pujara'\n 'Cheteshwar Pujara' 'Murali Vijay' 'Murali Vijay' 'Murali Vijay'\n 'Naman Ojha' 'Naman Ojha' 'Naman Ojha' 'Srikar Bharat' 'Srikar Bharat'\n 'Srikar Bharat' 'ricky Bhui' 'ricky Bhui' 'ricky Bhui'\n 'Jyothi Sai Krishan' 'Jyothi Sai Krishan' 'Jyothi Sai Krishan' 'z'\n 'Himanshu Asnora'] not in index"

In [ ]:
dataset.iloc[:,1]=mt_new 
mt_new

In [ ]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder( categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [ ]:
X

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegressionCV
# linear
model = LogisticRegressionCV()

In [ ]:
model.fit(X_train ,y_train)

In [ ]:
y_predict=model.predict(X_test)

y_predict

In [ ]:
y_test.values

In [ ]:
from sklearn.metrics import accuracy_score, f1_score

accuracy_score(y_test,y_predict)

In [ ]:
f1_score(y_test, y_predict)

In [ ]:
dataset = pd.read_csv("bowler_1.csv")

In [ ]:
dataset = dataset.fillna(0)
dataset

In [ ]:
y = dataset.iloc[: , -1]

In [ ]:
y

In [ ]:
X = dataset.iloc[: , 0:13]

In [ ]:
X

In [ ]:
name = dataset.iloc[: ,0 ]

In [ ]:
mt = X.iloc[:,1]
mt

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
mt_new = labelencoder_x.fit_transform(mt)
X.iloc[:,1]= mt_new

In [ ]:
# preprocess :  categorical variable
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
name_new = labelencoder_x.fit_transform(name)
X.iloc[:,0]=name_new

In [ ]:
X

In [ ]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()

In [ ]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [ ]:
dataset.iloc[:,1]=mt_new 
mt_new

In [ ]:
from sklearn.preprocessing  import OneHotEncoder
onehotencoder = OneHotEncoder( categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [ ]:
X

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [ ]:
model.fit(X_train ,y_train)

In [ ]:
model.predict(X_test)

In [ ]:
y_test