In [27]:
import numpy as np
import pandas as pd

In [28]:
dataset = pd.read_csv("bowler_1.csv")

In [29]:
dataset = dataset.fillna(0)
dataset

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10,capped
0,Praveen Kumar,First-class,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1,1
1,Praveen Kumar,List A,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0,1
2,Praveen Kumar,T20s,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0,1
3,Akshdeep Nath,First-class,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0,0
4,Akshdeep Nath,List A,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0,0
5,Akshdeep Nath,T20s,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0,0
6,Amit Mishra,First-class,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1,1
7,Amit Mishra,List A,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0,1
8,Amit Mishra,T20s,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0,1
9,Piyush Chawla,First-class,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3,1
10,Piyush Chawla,List A,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0,1
11,Piyush Chawla,T20s,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0,0
12,Mohammad Saif,First-class,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0,0
13,Mohammad Saif,List A,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0,0
14,Ankit Rajpoot,First-class,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1,0
15,Ankit Rajpoot,List A,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0,0
16,Ankit Rajpoot,T20s,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0,0
17,Deependra Pandey,List A,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0,0
18,Deependra Pandey,T20s,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0,0
19,JaydevUnadkat,First-class,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2,1
20,JaydevUnadkat,List A,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0,1
21,JaydevUnadkat,T20s,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0,1
22,Hardik Rathod,First-class,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0,0
23,Hardik Rathod,List A,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0,0
24,Hardik Rathod,T20s,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0,0
25,Dhawal Kulkarni,First-class,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1,1
26,Dhawal Kulkarni,List A,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0,1
27,Dhawal Kulkarni,T20s,118,117.0,2354,3075,123,25.00,7.83,19.1,1.0,0.0,0,1
28,Harmeet Singh,First-class,23,43.0,4720,2369,70,33.84,3.01,67.4,3.0,3.0,0,0
29,Harmeet Singh,List A,11,11.0,540,363,14,25.92,4.03,38.5,0.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,jayant yadav,T20s,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0,0
112,tinu kundu,First-class,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1,0
113,ashok dinda,First-class,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5,1
114,ashok dinda,List A,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0,1
115,ashok dinda,T20s,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0,1
116,mukesh kumar,First-class,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0,0
117,mukesh kumar,List A,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0,0
118,mukesh kumar,T20s,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0,0
119,pradipta pramika,First-class,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0,0
120,pradipta pramika,List A,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0,0
121,pradipta pramika,T20s,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0,0
122,ishan porel,First-class,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0,0
123,ishan porel,List A,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0,0
124,prayas ray barman,List A,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0,0
125,shahbaz ahmed,First-class,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0,0
126,shahbaz ahmed,List A,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0,0
127,bandaru ayyappa,First-class,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0,0
128,bandaru ayyappa,List A,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0,0
129,bandaru ayyappa,T20s,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0,0
130,karthik Raman,First-class,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0,0
131,karthik Raman,List A,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0,0
132,karthik Raman,T20s,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0,0
133,karn sharma,First-class,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1,0
134,karn sharma,List A,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0,0
135,karn sharma,T20s,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0,0
136,Paisikalva Vijaykumar,First-class,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1,0
137,Paisikalva Vijaykumar,List A,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0,0
138,Paisikalva Vijaykumar,T20s,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0,0
139,Prithvi Raj,First-class,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0,0
140,Prithvi Raj,List A,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0,0

In [30]:
y = dataset.iloc[: , -1]
#y

In [31]:
X = dataset.iloc[: , 0:13]
# X

In [32]:
name = dataset.iloc[: ,0 ]
#name

In [33]:
mt = X.iloc[:,1]
#mt

In [34]:

dataset

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10,capped
0,Praveen Kumar,First-class,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1,1
1,Praveen Kumar,List A,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0,1
2,Praveen Kumar,T20s,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0,1
3,Akshdeep Nath,First-class,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0,0
4,Akshdeep Nath,List A,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0,0
5,Akshdeep Nath,T20s,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0,0
6,Amit Mishra,First-class,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1,1
7,Amit Mishra,List A,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0,1
8,Amit Mishra,T20s,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0,1
9,Piyush Chawla,First-class,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3,1
10,Piyush Chawla,List A,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0,1
11,Piyush Chawla,T20s,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0,0
12,Mohammad Saif,First-class,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0,0
13,Mohammad Saif,List A,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0,0
14,Ankit Rajpoot,First-class,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1,0
15,Ankit Rajpoot,List A,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0,0
16,Ankit Rajpoot,T20s,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0,0
17,Deependra Pandey,List A,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0,0
18,Deependra Pandey,T20s,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0,0
19,JaydevUnadkat,First-class,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2,1
20,JaydevUnadkat,List A,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0,1
21,JaydevUnadkat,T20s,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0,1
22,Hardik Rathod,First-class,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0,0
23,Hardik Rathod,List A,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0,0
24,Hardik Rathod,T20s,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0,0
25,Dhawal Kulkarni,First-class,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1,1
26,Dhawal Kulkarni,List A,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0,1
27,Dhawal Kulkarni,T20s,118,117.0,2354,3075,123,25.00,7.83,19.1,1.0,0.0,0,1
28,Harmeet Singh,First-class,23,43.0,4720,2369,70,33.84,3.01,67.4,3.0,3.0,0,0
29,Harmeet Singh,List A,11,11.0,540,363,14,25.92,4.03,38.5,0.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,jayant yadav,T20s,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0,0
112,tinu kundu,First-class,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1,0
113,ashok dinda,First-class,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5,1
114,ashok dinda,List A,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0,1
115,ashok dinda,T20s,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0,1
116,mukesh kumar,First-class,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0,0
117,mukesh kumar,List A,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0,0
118,mukesh kumar,T20s,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0,0
119,pradipta pramika,First-class,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0,0
120,pradipta pramika,List A,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0,0
121,pradipta pramika,T20s,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0,0
122,ishan porel,First-class,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0,0
123,ishan porel,List A,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0,0
124,prayas ray barman,List A,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0,0
125,shahbaz ahmed,First-class,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0,0
126,shahbaz ahmed,List A,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0,0
127,bandaru ayyappa,First-class,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0,0
128,bandaru ayyappa,List A,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0,0
129,bandaru ayyappa,T20s,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0,0
130,karthik Raman,First-class,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0,0
131,karthik Raman,List A,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0,0
132,karthik Raman,T20s,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0,0
133,karn sharma,First-class,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1,0
134,karn sharma,List A,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0,0
135,karn sharma,T20s,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0,0
136,Paisikalva Vijaykumar,First-class,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1,0
137,Paisikalva Vijaykumar,List A,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0,0
138,Paisikalva Vijaykumar,T20s,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0,0
139,Prithvi Raj,First-class,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0,0
140,Prithvi Raj,List A,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0,0

In [35]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
mt_new = labelencoder_x.fit_transform(mt)
X.iloc[:,1]= mt_new.astype(int)

In [36]:
# preprocess :  categorical variable
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
name_new = labelencoder_x.fit_transform(name)
X.iloc[:,0]=name_new.astype(int)
dataset.iloc[:,0] = name_new.astype(int)

In [37]:
a = X.name.unique()
a.sort()

In [38]:
# from sklearn.preprocessing  import OneHotEncoder
# onehotencoder = OneHotEncoder(categorical_features=[0])
# X = onehotencoder.fit_transform(X).toarray()

In [13]:
# from sklearn.preprocessing  import OneHotEncoder
# onehotencoder = OneHotEncoder(categorical_features=[1])
# X = onehotencoder.fit_transform(X).toarray()

In [39]:
dataset

,name,mt,Mat,Inns,Balls,Runs,Wkts,Ave,Econ,SR,4w,5w,10,capped
0,19,First-class,66,121.0,14158,6306,267,23.61,2.67,53.0,16.0,17.0,1,1
1,19,List A,139,0.0,6730,5336,185,28.84,4.75,36.3,4.0,2.0,0,1
2,19,T20s,177,177.0,3695,4599,143,32.16,7.46,25.8,0.0,0.0,0,1
3,0,First-class,22,12.0,366,179,6,29.83,2.93,61.0,0.0,0.0,0,0
4,0,List A,44,14.0,360,327,13,25.15,5.45,27.6,0.0,0.0,0,0
5,0,T20s,51,15.0,177,241,12,20.08,8.16,14.7,0.0,0.0,0,0
6,1,First-class,152,0.0,30843,15608,535,29.17,3.03,57.6,0.0,21.0,1,1
7,1,List A,144,0.0,7426,5681,242,23.47,4.59,30.6,7.0,6.0,0,1
8,1,T20s,199,198.0,4168,4970,228,21.79,7.15,18.2,4.0,2.0,0,1
9,17,First-class,130,227.0,26086,14276,437,32.66,3.28,59.6,22.0,23.0,3,1
10,17,List A,131,127.0,6487,5363,208,25.78,4.96,31.1,7.0,3.0,0,1
11,17,T20s,208,207.0,4290,5379,218,24.67,7.52,19.6,3.0,0.0,0,0
12,14,First-class,17,18.0,451,252,3,84.00,3.35,150.3,0.0,0.0,0,0
13,14,List A,5,4.0,150,174,3,58.00,6.96,50.0,0.0,0.0,0,0
14,2,First-class,50,89.0,9429,4761,174,27.36,3.02,54.1,9.0,8.0,1,0
15,2,List A,30,29.0,1421,1152,36,32.00,4.86,39.4,0.0,0.0,0,0
16,2,T20s,54,54.0,1078,1351,68,19.86,7.51,15.8,1.0,2.0,0,0
17,3,List A,1,1.0,42,36,0,0.00,5.14,0.0,0.0,0.0,0,0
18,3,T20s,1,1.0,6,9,0,0.00,9.00,0.0,0.0,0.0,0,0
19,10,First-class,73,125.0,12392,6172,233,26.48,2.98,53.1,11.0,12.0,2,1
20,10,List A,84,84.0,4416,3549,116,30.59,4.82,38.0,5.0,1.0,0,1
21,10,T20s,110,109.0,2331,3054,134,22.79,7.86,17.3,0.0,2.0,0,1
22,6,First-class,18,29.0,2942,1508,38,39.68,3.07,77.4,0.0,1.0,0,0
23,6,List A,3,3.0,78,76,0,0.00,5.84,0.0,0.0,0.0,0,0
24,6,T20s,5,5.0,106,141,2,70.50,7.98,53.0,0.0,0.0,0,0
25,4,First-class,86,140.0,15531,7174,261,27.48,2.77,59.5,9.0,15.0,1,1
26,4,List A,110,109.0,5461,4308,187,23.03,4.73,29.2,5.0,3.0,0,1
27,4,T20s,118,117.0,2354,3075,123,25.00,7.83,19.1,1.0,0.0,0,1
28,7,First-class,23,43.0,4720,2369,70,33.84,3.01,67.4,3.0,3.0,0,0
29,7,List A,11,11.0,540,363,14,25.92,4.03,38.5,0.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,39,T20s,40,36.0,700,695,20,34.75,5.95,35.0,0.0,0.0,0,0
112,48,First-class,4,7.0,799,317,24,13.20,2.38,33.2,1.0,2.0,1,0
113,33,First-class,115,194.0,22866,11823,417,28.35,3.10,54.8,19.0,26.0,5,1
114,33,List A,92,92.0,4686,4015,141,28.47,5.14,33.2,2.0,3.0,0,1
115,33,T20s,133,130.0,2695,3441,132,26.06,7.66,20.4,3.0,0.0,0,1
116,43,First-class,12,22.0,2170,1045,48,21.77,2.88,45.2,3.0,2.0,0,0
117,43,List A,8,8.0,384,325,5,65.00,5.07,76.8,0.0,0.0,0,0
118,43,T20s,6,6.0,126,145,6,24.16,6.90,21.0,0.0,0.0,0,0
119,44,First-class,7,12.0,1275,614,25,24.56,2.88,51.0,2.0,0.0,0,0
120,44,List A,8,8.0,384,296,12,24.66,4.62,32.0,1.0,0.0,0,0
121,44,T20s,1,1.0,12,24,0,0.00,12.00,0.0,0.0,0.0,0,0
122,37,First-class,12,18.0,1909,906,32,28.31,2.84,59.6,2.0,2.0,0,0
123,37,List A,9,9.0,366,296,12,24.66,4.85,30.5,1.0,0.0,0,0
124,45,List A,9,9.0,341,253,11,23.00,4.45,31.0,1.0,0.0,0,0
125,47,First-class,2,3.0,180,80,2,40.00,2.66,90.0,0.0,0.0,0,0
126,47,List A,6,6.0,210,160,6,26.66,4.57,35.0,0.0,0.0,0,0
127,34,First-class,29,48.0,5175,2566,77,33.32,2.97,67.2,3.0,3.0,0,0
128,34,List A,31,31.0,1620,1337,43,31.09,4.95,37.6,1.0,0.0,0,0
129,34,T20s,26,26.0,557,667,31,21.51,7.18,17.9,0.0,0.0,0,0
130,41,First-class,4,6.0,462,255,9,28.33,3.31,51.3,0.0,0.0,0,0
131,41,List A,8,8.0,361,313,14,22.35,5.20,25.7,2.0,0.0,0,0
132,41,T20s,3,1.0,12,23,0,0.00,11.50,0.0,0.0,0.0,0,0
133,40,First-class,69,107.0,10155,5381,188,28.62,3.17,54.0,8.0,10.0,1,0
134,40,List A,80,75.0,3805,3001,99,30.31,4.73,38.4,0.0,2.0,0,0
135,40,T20s,119,109.0,2027,2483,101,24.58,7.34,20.0,2.0,1.0,0,0
136,16,First-class,69,118.0,14608,5386,239,22.53,2.21,61.1,10.0,10.0,1,0
137,16,List A,28,28.0,1448,1034,34,30.41,4.28,42.5,1.0,0.0,0,0
138,16,T20s,18,18.0,342,466,10,46.60,8.17,34.2,0.0,0.0,0,0
139,20,First-class,6,11.0,1036,512,21,24.38,2.96,49.3,1.0,0.0,0,0
140,20,List A,1,1.0,60,65,2,32.50,6.50,30.0,0.0,0.0,0,0

In [40]:
dataset.iloc[:,1]=mt_new 
#mt_new

In [16]:
# from sklearn.preprocessing  import OneHotEncoder
# onehotencoder = OneHotEncoder( categorical_features=[1])
# X = onehotencoder.fit_transform(X).toarray()

In [41]:
X[X["name"]==12]

    name  mt  Mat  Inns  Balls  Runs  Wkts    Ave  Econ    SR   4w   5w  10
58    12   0   30  49.0   5774  3512   117  30.01  3.64  49.3  7.0  6.0   0
59    12   1   44  42.0   2274  1777    83  21.40  4.68  27.3  2.0  2.0   0
60    12   2   79  78.0   1695  2073   106  19.55  7.33  15.9  3.0  2.0   0

In [48]:
#import itertools
#features = []
#for i in a:
    #features.append(list(itertools.chain(*X[X["name"]==i].iloc[:,2:].values)))
#features=pd.DataFrame(features)
#features

In [49]:
targets = []
for i in a:
    targets.append(any(dataset[dataset["name"]==i]["capped"]))
#targets

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.20, random_state=42)

In [52]:
from sklearn.linear_model import LogisticRegressionCV

model = LogisticRegressionCV()

In [54]:
model.fit(X_train ,y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [24]:
model.predict(X_test)

NotFittedError: This LogisticRegressionCV instance is not fitted yet

In [55]:
y_test

[False, False, False, False, True, True, True, False, True, True]